import { DATA_LOOKUP_ENTITY_KEYS } from './dataLookupRegistry.js'

export const METRICS = {
  actual_hours: 'Actual Hours',
  cancelled_count: 'Cancelled Shifts',
  completed_count: 'Completed Shifts',
  completion_rate: 'Completion Rate',
  fill_rate: 'Fill Rate',
  employee_count: 'Employees',
  record_count: 'Records',
  missed_count: 'Missed Shifts',
  rostered_hours: 'Rostered Hours',
  shift_count: 'Shift Count',
  unfilled_count: 'Unfilled Shifts',
}

export const GROUPINGS = [
  'attendance_status',
  'customer',
  'date',
  'day',
  'department',
  'employee',
  'month',
  'position',
  'shift_status',
  'site',
  'week',
]

export const CHART_TYPES = ['bar', 'line', 'pie']

const DATA_LOOKUP_SORT_FIELDS = [
  'actual_hours',
  'attendance_status',
  'customer_name',
  'department',
  'employee_count',
  'employee_name',
  'position',
  'record_count',
  'rostered_hours',
  'scheduled_start',
  'shift_date',
  'shift_status',
  'site_name',
  'status',
]

export const REPORT_TYPES = {
  attendance_exceptions: {
    allowedChartTypes: ['bar'],
    allowedGroupBy: ['employee', 'customer', 'site', 'date', 'week', 'month', 'attendance_status'],
    allowedMetrics: ['missed_count', 'unfilled_count', 'cancelled_count'],
    allowedSortFields: ['missed_count', 'unfilled_count', 'cancelled_count'],
    defaultChartType: 'bar',
    defaultGroupBy: 'employee',
    defaultMetrics: ['missed_count', 'unfilled_count'],
    label: 'Attendance Exceptions',
    method: 'getAttendanceExceptions',
  },
  currently_clocked_in: {
    allowedChartTypes: ['bar'],
    allowedGroupBy: ['employee', 'customer', 'site'],
    allowedMetrics: ['shift_count', 'actual_hours'],
    allowedSortFields: ['shift_count', 'actual_hours'],
    defaultChartType: 'bar',
    defaultGroupBy: 'employee',
    defaultMetrics: ['shift_count'],
    label: 'Currently Clocked In',
    method: 'getCurrentlyClockedIn',
  },
  customer_performance: {
    allowedChartTypes: ['bar', 'line'],
    allowedGroupBy: ['customer', 'date', 'week', 'month'],
    allowedMetrics: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'fill_rate', 'rostered_hours', 'actual_hours'],
    allowedSortFields: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'fill_rate', 'rostered_hours', 'actual_hours'],
    defaultChartType: 'bar',
    defaultGroupBy: 'customer',
    defaultMetrics: ['shift_count', 'completed_count', 'missed_count'],
    label: 'Customer Shift Comparison',
    method: 'getCustomerPerformance',
  },
  employee_directory: {
    allowedChartTypes: ['bar', 'pie'],
    allowedGroupBy: ['employee', 'department', 'position'],
    allowedMetrics: ['employee_count'],
    allowedSortFields: ['employee_name', 'department', 'position', 'employee_count'],
    defaultChartType: 'bar',
    defaultGroupBy: 'department',
    defaultMetrics: ['employee_count'],
    label: 'Employee Directory',
    method: 'getEmployeeDirectory',
    tableColumns: [
      { key: 'employee_name', label: 'Employee Name' },
      { key: 'department', label: 'Department' },
      { key: 'position', label: 'Position' },
      { key: 'status', label: 'Status' },
    ],
    usesDateRange: false,
  },
  data_lookup: {
    allowedChartTypes: ['bar', 'pie'],
    allowedEntities: DATA_LOOKUP_ENTITY_KEYS,
    allowedGroupBy: GROUPINGS,
    allowedMetrics: ['record_count'],
    allowedSortFields: DATA_LOOKUP_SORT_FIELDS,
    defaultChartType: 'bar',
    defaultEntity: 'employees',
    defaultGroupBy: 'employee',
    defaultMetrics: ['record_count'],
    label: 'FieldServicer Data Lookup',
    method: 'getDataLookup',
    usesDateRange: false,
  },
  employee_hours: {
    allowedChartTypes: ['bar', 'line'],
    allowedGroupBy: ['employee', 'department', 'position', 'date', 'week', 'month'],
    allowedMetrics: ['rostered_hours', 'actual_hours'],
    allowedSortFields: ['rostered_hours', 'actual_hours'],
    defaultChartType: 'bar',
    defaultGroupBy: 'employee',
    defaultMetrics: ['rostered_hours', 'actual_hours'],
    label: 'Employee Hours',
    method: 'getEmployeeHours',
  },
  employee_shift_count: {
    allowedChartTypes: ['bar'],
    allowedGroupBy: ['employee', 'department', 'position'],
    allowedMetrics: ['shift_count', 'completed_count', 'missed_count'],
    allowedSortFields: ['shift_count', 'completed_count', 'missed_count'],
    defaultChartType: 'bar',
    defaultGroupBy: 'employee',
    defaultMetrics: ['shift_count'],
    label: 'Employee Shift Count',
    method: 'getEmployeeShiftCount',
  },
  missed_shifts: {
    allowedChartTypes: ['bar', 'line', 'pie'],
    allowedGroupBy: ['employee', 'customer', 'site', 'date', 'week', 'month'],
    allowedMetrics: ['missed_count'],
    allowedSortFields: ['missed_count'],
    defaultChartType: 'bar',
    defaultGroupBy: 'site',
    defaultMetrics: ['missed_count'],
    label: 'Missed Shifts',
    method: 'getMissedShifts',
  },
  shift_status_summary: {
    allowedChartTypes: ['bar', 'pie'],
    allowedGroupBy: ['shift_status', 'customer', 'site', 'date', 'week', 'month'],
    allowedMetrics: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'cancelled_count', 'completion_rate', 'fill_rate'],
    allowedSortFields: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'cancelled_count'],
    defaultChartType: 'bar',
    defaultGroupBy: 'shift_status',
    defaultMetrics: ['shift_count'],
    label: 'Shift Status Summary',
    method: 'getShiftStatusSummary',
  },
  shift_trend: {
    allowedChartTypes: ['line', 'bar'],
    allowedGroupBy: ['date', 'week', 'month'],
    allowedMetrics: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'fill_rate'],
    allowedSortFields: ['date', 'week', 'month', 'shift_count'],
    defaultChartType: 'line',
    defaultGroupBy: 'week',
    defaultMetrics: ['shift_count'],
    label: 'Shift Trend',
    method: 'getShiftTrend',
  },
  site_performance: {
    allowedChartTypes: ['bar', 'line'],
    allowedGroupBy: ['site', 'customer', 'date', 'week', 'month'],
    allowedMetrics: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'fill_rate', 'rostered_hours', 'actual_hours'],
    allowedSortFields: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count', 'fill_rate', 'rostered_hours', 'actual_hours'],
    defaultChartType: 'bar',
    defaultGroupBy: 'site',
    defaultMetrics: ['shift_count', 'completed_count', 'missed_count', 'unfilled_count'],
    label: 'Site Coverage Comparison',
    method: 'getSitePerformance',
  },
}

export function getReportDefinition(reportType) {
  return REPORT_TYPES[reportType] ?? null
}

export function listReportTypes() {
  return Object.entries(REPORT_TYPES).map(([key, definition]) => ({
    chartTypes: definition.allowedChartTypes,
    entities: definition.allowedEntities,
    defaultChartType: definition.defaultChartType,
    defaultGroupBy: definition.defaultGroupBy,
    label: definition.label,
    metrics: definition.allowedMetrics,
    reportType: key,
  }))
}
